# Generated by Django 4.2.1 on 2023-05-10 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rutAdmin', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut Administrador')),
                ('nombreAdmin', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaternoAdmin', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaternoAdmin', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('correoAdmin', models.CharField(max_length=35, verbose_name='Correo')),
                ('contrasenaAdmin', models.CharField(max_length=12, verbose_name='Contrasenia')),
                ('numeroTelefonoAdmin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rutProf', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut Administrador')),
                ('nombreProf', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaternoProf', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaternoProf', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correoProf', models.CharField(max_length=35, verbose_name='Correo')),
                ('contrasenaProf', models.CharField(max_length=12, verbose_name='Contrasenia')),
                ('numeroTelefonoProf', models.IntegerField()),
                ('regionProf', models.CharField(max_length=30, verbose_name='Region')),
                ('comunaProf', models.CharField(max_length=30, verbose_name='Comuna')),
                ('fotoPerfil', models.BinaryField(verbose_name='Foto de perfil')),
            ],
        ),
        migrations.CreateModel(
            name='profesion',
            fields=[
                ('codigoVerificador', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo verificador')),
                ('institucion', models.CharField(max_length=30, verbose_name='Institucion')),
                ('profesion', models.CharField(max_length=30, verbose_name='Profesion')),
                ('anioEgreso', models.DateField()),
                ('tituloValidado', models.CharField(max_length=9, null=True, verbose_name='Titulo validado')),
                ('rutProfProfesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
        ),
    ]
