# Generated by Django 4.2.1 on 2023-05-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellidoMaterno',
        ),
    ]
