# Generated by Django 4.2.1 on 2023-06-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_asignatura_nombreasignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default='2023-06-02', verbose_name='Fecha de solicitud'),
        ),
    ]
