# Generated by Django 4.2.1 on 2023-05-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profesor_profesion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profesion',
            new_name='profesione',
        ),
    ]
