# Generated by Django 4.2.1 on 2023-06-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solicitud_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
    ]
