# Generated by Django 4.2.1 on 2023-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_publicacion_idasignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcionPublicacion',
            field=models.TextField(verbose_name='Descripcion de la publicacion'),
        ),
    ]
