# Generated by Django 4.2.1 on 2023-05-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_estudiante_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
