# Generated by Django 4.2.1 on 2023-05-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_estudiante_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('idDescripcion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Descripcion')),
                ('descripcionTutor', models.CharField(max_length=100, verbose_name='Descripicion del tutor')),
                ('rutProfDesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
        ),
    ]
