# Generated by Django 4.2.1 on 2023-06-05 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_descripcion_idprofesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='idProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clase', to=settings.AUTH_USER_MODEL),
        ),
    ]
