# Generated by Django 4.2.1 on 2023-05-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='descripcion',
            options={'verbose_name': 'Descripcion', 'verbose_name_plural': 'Descripciones'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name': 'Profesion', 'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='Administrador',
        ),
        migrations.AlterModelTable(
            name='descripcion',
            table='Descripcion',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='Estudiante',
        ),
        migrations.AlterModelTable(
            name='profesion',
            table='Profesion',
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='Profesor',
        ),
    ]
