# Generated by Django 4.2.1 on 2023-05-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Administradorr',
        ),
        migrations.RenameModel(
            old_name='descripcion',
            new_name='descripcionn',
        ),
        migrations.RenameModel(
            old_name='estudiante',
            new_name='estudiantee',
        ),
        migrations.RenameModel(
            old_name='profesion',
            new_name='profesionn',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesorr',
        ),
    ]
