# Generated by Django 4.2.1 on 2023-06-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_clase_idprofesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='descripcionAsignatura',
            field=models.TextField(verbose_name='Descripcion de la asignatura'),
        ),
    ]
