# Generated by Django 4.2.1 on 2023-05-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_administrador_administradorr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administradorr',
            new_name='Administrador',
        ),
        migrations.RenameModel(
            old_name='descripcionn',
            new_name='descripcion',
        ),
        migrations.RenameModel(
            old_name='estudiantee',
            new_name='estudiante',
        ),
        migrations.RenameModel(
            old_name='profesionn',
            new_name='profesion',
        ),
        migrations.RenameModel(
            old_name='Profesorr',
            new_name='Profesor',
        ),
    ]
