# Generated by Django 4.2.1 on 2023-06-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_asignatura_descripcionasignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombreAsignatura',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la asignatura'),
        ),
    ]
