# Generated by Django 4.2.1 on 2023-06-06 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_asignatura_nombreasignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='idEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
