# Generated by Django 4.2.1 on 2023-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_administradorr_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcion',
            name='rutProfDesc',
        ),
        migrations.DeleteModel(
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='profesion',
            name='rutProfProfesion',
        ),
        migrations.DeleteModel(
            name='descripcion',
        ),
        migrations.DeleteModel(
            name='profesion',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
