# Generated by Django 4.2.1 on 2023-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_descripcion_rutprofdesc_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
