# Generated by Django 4.2.1 on 2023-05-10 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_delete_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rutAdmin', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut Administrador')),
                ('nombreAdmin', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaternoAdmin', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaternoAdmin', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('correoAdmin', models.CharField(max_length=35, verbose_name='Correo')),
                ('contrasenaAdmin', models.CharField(max_length=12, verbose_name='Contrasenia')),
                ('numeroTelefonoAdmin', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('rutEst', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut Estudiante')),
                ('nombreEst', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaternoEst', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaternoEst', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correoEst', models.CharField(max_length=35, verbose_name='Correo')),
                ('contrasenaEst', models.CharField(max_length=12, verbose_name='Contrasenia')),
                ('numeroTelefonoEst', models.IntegerField()),
                ('regionEst', models.CharField(max_length=30, verbose_name='Region')),
                ('comunaEst', models.CharField(max_length=30, verbose_name='Comuna')),
                ('fotoPerfil', models.BinaryField(verbose_name='Foto de perfil')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rutProf', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut Profesor')),
                ('nombreProf', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaternoProf', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaternoProf', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correoProf', models.CharField(max_length=35, verbose_name='Correo')),
                ('contrasenaProf', models.CharField(max_length=12, verbose_name='Contrasenia')),
                ('numeroTelefonoProf', models.IntegerField()),
                ('regionProf', models.CharField(max_length=30, verbose_name='Region')),
                ('comunaProf', models.CharField(max_length=30, verbose_name='Comuna')),
                ('fotoPerfil', models.BinaryField(verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'Profesor',
            },
        ),
        migrations.CreateModel(
            name='profesion',
            fields=[
                ('codigoVerificador', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo verificador')),
                ('institucion', models.CharField(max_length=30, verbose_name='Institucion')),
                ('profesion', models.CharField(max_length=30, verbose_name='Profesion')),
                ('anioEgreso', models.DateField()),
                ('tituloValidado', models.CharField(max_length=9, null=True, verbose_name='Titulo validado')),
                ('rutProfProfesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'Profesion',
            },
        ),
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('idDescripcion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Descripcion')),
                ('descripcionTutor', models.CharField(max_length=100, verbose_name='Descripicion del tutor')),
                ('rutProfDesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'Descripciones',
                'db_table': 'Descripcion',
            },
        ),
    ]
