# Generated by Django 4.2.1 on 2023-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Asignatura')),
                ('nombreAsignatura', models.CharField(max_length=30, verbose_name='Nombre asignatura')),
                ('carreraPerteneciente', models.CharField(max_length=30, verbose_name='Carrera a la que pertenece')),
                ('descripcionAsignatura', models.CharField(max_length=500, verbose_name='Descripcion asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'Asignatura',
            },
        ),
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campoPrueba', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'db_table': 'Prueba',
            },
        ),
    ]
