# Generated by Django 4.2.1 on 2023-05-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_asignatura_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
