# Generated by Django 4.2.1 on 2023-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_estudiante_fotoperfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='modalidad',
            field=models.CharField(max_length=10, verbose_name='Modalidad'),
        ),
    ]
