# Generated by Django 4.2.1 on 2023-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_clase_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='idAsignaturaClase',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='rutProfClase',
        ),
        migrations.RemoveField(
            model_name='descripcion',
            name='rutProfDesc',
        ),
        migrations.AlterField(
            model_name='profesion',
            name='tituloValidado',
            field=models.CharField(max_length=9, null=True, verbose_name='Titulo validado'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='descripcion',
        ),
    ]
