# Generated by Django 4.2.1 on 2023-05-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_clase_idasignaturaclase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionTutor', models.CharField(max_length=100, verbose_name='Descripicion del tutor')),
                ('rutProfDesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'Descripciones',
                'db_table': 'Descripcion',
            },
        ),
    ]
