# Generated by Django 4.2.1 on 2023-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsignatura', models.CharField(max_length=30, verbose_name='Nombre de la asignatura')),
                ('carreraPerteneciente', models.CharField(max_length=30, verbose_name='Carrera a la que pertenece')),
                ('descripcionAsignatura', models.CharField(max_length=500, verbose_name='Descripcion de la asignatura')),
            ],
        ),
    ]
