# Generated by Django 4.2.1 on 2023-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_asignatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelTable(
            name='asignatura',
            table='Asignatura',
        ),
    ]
