# Generated by Django 4.2.1 on 2023-05-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_asignatura_options_alter_asignatura_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='anioEgreso',
            field=models.DateField(verbose_name='Anio de egreso'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la clase')),
                ('hora', models.TimeField(verbose_name='Hora de la clase')),
                ('modalidad', models.CharField(max_length=10, verbose_name='Modadlidad de la clase')),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
                ('rutProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'Clase',
            },
        ),
    ]
