# Generated by Django 4.2.1 on 2023-05-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_profesion_anioegreso_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo de la publicacion')),
                ('descripcionPublicacion', models.CharField(max_length=100, verbose_name='Descripcion de la publicacion')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de la publicacion')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora de la publicacion')),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
                ('rutEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'Publicacion',
            },
        ),
    ]
