# Generated by Django 4.2.1 on 2023-05-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='rutProf',
            new_name='rutProfClase',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='rutEst',
            new_name='rutEstPublicacion',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=50, verbose_name='Comentario')),
                ('valoracion', models.IntegerField(default=1, max_length=1, verbose_name='Valoracion')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del comentario')),
                ('rutEstComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('rutProfComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'Comentario',
            },
        ),
    ]
