# Generated by Django 4.2.1 on 2023-05-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_rutprof_clase_rutprofclase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='rutProfClase',
            new_name='rutProf',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='rutEstComentario',
            new_name='rutEst',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='rutProfComentario',
            new_name='rutProf',
        ),
        migrations.RenameField(
            model_name='descripcion',
            old_name='rutProfDesc',
            new_name='rutProf',
        ),
        migrations.RenameField(
            model_name='profesion',
            old_name='rutProfProfesion',
            new_name='rutProf',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='rutEstPublicacion',
            new_name='rutEst',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='valoracion',
            field=models.IntegerField(default=1, verbose_name='Valoracion'),
        ),
    ]
