# Generated by Django 4.2.1 on 2023-05-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_rutprofclase_clase_rutprof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idClase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clase')),
                ('rutEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('rutProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
            options={
                'verbose_name': 'Clase Agendada',
                'verbose_name_plural': 'Clases Agendadas',
                'db_table': 'ClaseAgendada',
            },
        ),
    ]
