# Generated by Django 4.2.1 on 2023-05-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_clase_tarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Notificacion')),
                ('rutEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notificacion',
            },
        ),
    ]
