# Generated by Django 4.2.1 on 2023-05-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_delete_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipoDeUsuario',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Tutor', 'Tutor')], default='Estudiante', max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
