# Generated by Django 4.2.1 on 2023-05-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_profesion_rutprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesion',
            old_name='rutProf',
            new_name='idProfesor',
        ),
    ]
