# Generated by Django 4.2.1 on 2023-05-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_rutprof_profesion_idprofesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='idProfesor',
        ),
        migrations.AddField(
            model_name='profesion',
            name='rutProf',
            field=models.ForeignKey(default='X', on_delete=django.db.models.deletion.CASCADE, to='api.profesor'),
            preserve_default=False,
        ),
    ]
